[2024-11-25 00:22:28,631][flwr][DEBUG] - Pre-registering run with id 3634779472047321155
[2024-11-25 00:22:28,632][flwr][DEBUG] - Using InMemoryState
[2024-11-25 00:22:28,632][flwr][DEBUG] - Using InMemoryState
[2024-11-25 00:22:28,643][flwr][DEBUG] - Buffer time delay: 5s
[2024-11-25 00:22:28,737][flwr][WARNING] - 
Setting `min_available_clients` lower than `min_fit_clients` or
`min_evaluate_clients` can cause the server to fail when there are too few clients
connected to the server. `min_available_clients` must be set to a value larger
than or equal to the values of `min_fit_clients` and `min_evaluate_clients`.

[2024-11-25 00:22:28,737][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=3, no round_timeout
[2024-11-25 00:22:28,738][flwr][INFO] - 
[2024-11-25 00:22:28,738][flwr][INFO] - [INIT]
[2024-11-25 00:22:28,738][flwr][INFO] - Using initial global parameters provided by strategy
[2024-11-25 00:22:28,738][flwr][INFO] - Starting evaluation of initial global parameters
[2024-11-25 00:22:28,738][flwr][INFO] - Evaluation returned no results (`None`)
[2024-11-25 00:22:28,738][flwr][INFO] - 
[2024-11-25 00:22:28,738][flwr][INFO] - [ROUND 1]
[2024-11-25 00:22:33,650][flwr][DEBUG] - Using InMemoryState
[2024-11-25 00:22:33,651][flwr][DEBUG] - Registered 10 nodes
[2024-11-25 00:22:33,655][flwr][DEBUG] - Supported backends: ['ray']
[2024-11-25 00:22:33,655][flwr][DEBUG] - Initialising: RayBackend
[2024-11-25 00:22:33,655][flwr][DEBUG] - Backend config: {'client_resources': {'num_cpus': 8}, 'init_args': {'logging_level': 30, 'log_to_driver': True}, 'actor': {'tensorflow': 0}}
[2024-11-25 00:22:34,748][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2024-11-25 00:22:36,232][flwr][DEBUG] - Constructed ActorPool with: 1 actors
[2024-11-25 00:22:36,232][flwr][DEBUG] - Using InMemoryState
[2024-11-25 00:23:46,688][flwr][DEBUG] - Terminated 1 actors
[2024-11-25 00:23:47,546][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2024-11-25 00:23:47,624][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-11-25 00:23:47,635][flwr][INFO] - configure_evaluate: strategy sampled 5 clients (out of 10)
[2024-11-25 00:23:47,635][flwr][ERROR] - ServerApp thread raised an exception: cannot schedule new futures after interpreter shutdown
[2024-11-25 00:23:47,637][flwr][ERROR] - Traceback (most recent call last):
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flwr/simulation/run_simulation.py", line 336, in server_th_with_start_checks
    run_server_app(
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flwr/server/run_serverapp.py", line 88, in run
    server_app(driver=driver, context=context)
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flwr/server/server_app.py", line 120, in __call__
    start_driver(
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flwr/server/compat/app.py", line 87, in start_driver
    hist = run_fl(
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flwr/server/server.py", line 492, in run_fl
    hist, elapsed_time = server.fit(
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flwr/server/server.py", line 145, in fit
    res_fed = self.evaluate_round(server_round=current_round, timeout=timeout)
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flwr/server/server.py", line 186, in evaluate_round
    results, failures = evaluate_clients(
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flwr/server/server.py", line 409, in evaluate_clients
    submitted_fs = {
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flwr/server/server.py", line 410, in <setcomp>
    executor.submit(evaluate_client, client_proxy, ins, timeout, group_id)
  File "/Users/tobias/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

[2024-11-25 00:23:47,637][flwr][DEBUG] - ServerApp finished running.
[2024-11-25 00:23:47,637][flwr][DEBUG] - Triggered stop event for Simulation Engine.
